# Generated by Django 3.2.8 on 2021-10-12 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211011_0717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_twiter',
            new_name='social_twitter',
        ),
    ]
