# Generated by Django 3.2.8 on 2021-10-15 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_text_message_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created', 'name']},
        ),
    ]
